### ISSUE TITLE
No such file or directory: './vgg16.npy'

### ISSUE THREAD

**Issue by divyachandana** [ZongxuPan/DrBox-v2-tensorflow#19]
DrBox-v2-tensorflow >: cat nlp.o2215624 
/opt/gridengine/default/spool/sge_execd/node413/job_scripts/2215624: line 1: ge:: command not found
Running on host: node413.
In directory: /home/d/dc593/DrBox-v2-tensorflow
Starting on: Tue Feb 25 13:00:06 EST 2020
WARNING: underlay of /usr/bin/nvidia-smi required more than 50 (384) bind mounts
2020-02-25 18:03:19.032410: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2020-02-25 18:03:19.032696: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2020-02-25 18:03:19.032711: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2020-02-25 18:03:19.032718: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2020-02-25 18:03:19.032724: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
Preprocessing 0
 [*] Reading checkpoints...
 [*] Failed to find a checkpoint
 [*] Load the pretrained network
Traceback (most recent call last):
  File "Drbox.py", line 469, in <module>
    net.train()
  File "Drbox.py", line 252, in train
    could_load, checkpoint_counter = self.load()
  File "Drbox.py", line 447, in load
    self.load_prenet()
  File "Drbox.py", line 451, in load_prenet
    data_list = np.load(PRETRAINED_NET_PATH).item()
  File "/home/user/miniconda/envs/py27/lib/python2.7/site-packages/numpy/lib/npyio.py", line 422, in load
    fid = open(os_fspath(file), "rb")
IOError: [Errno 2] No such file or directory: './vgg16.npy'
sge_job_epilog: Removed left over scratch directory  {/scratch/2215624.1.datasci}
node674-46 DrBox-v2-tensorflow >:

**Comment by divyachandana** [comment]
https://mega.nz/#!YU1FWJrA!O1ywiCS2IiOlUCtCpI6HTJOMrneN-Qdv3ywQP5poecM

solved the issue it has vgg16.npy file

**Comment by Untilseeuu** [comment]
thanks

**Comment by CookieThaRookie** [comment]
How did you get the file?
