### ISSUE TITLE
Problems with my own dataset

### ISSUE THREAD

**Issue by niuxiansen2** [ZongxuPan/DrBox-v2-tensorflow#4]
hello @ZongxuPan 

Is the size of the input image fixed? Why do I encounter the following problems with my own data set?

Traceback (most recent call last):
  File "Drbox.py", line 469, in <module>
    net.train()
  File "Drbox.py", line 284, in train
    input_im[k] = im.reshape(IM_HEIGHT, IM_WIDTH, IM_CDIM).astype('float32')
ValueError: cannot reshape array of size 496500 into shape (300,300,3)

**Comment by ZongxuPan** [comment]
> 
> 
> hello @ZongxuPan
> 
> Is the size of the input image fixed? Why do I encounter the following problems with my own data set?
> 
> Traceback (most recent call last):
> File "Drbox.py", line 469, in
> net.train()
> File "Drbox.py", line 284, in train
> input_im[k] = im.reshape(IM_HEIGHT, IM_WIDTH, IM_CDIM).astype('float32')
> ValueError: cannot reshape array of size 496500 into shape (300,300,3)

Please set IM_HEIGHT and IM_WIDTH as the desired values.

**Comment by ZongxuPan** [comment]
> 
> 
> hello @ZongxuPan
> 
> Is the size of the input image fixed? Why do I encounter the following problems with my own data set?
> 
> Traceback (most recent call last):
> File "Drbox.py", line 469, in
> net.train()
> File "Drbox.py", line 284, in train
> input_im[k] = im.reshape(IM_HEIGHT, IM_WIDTH, IM_CDIM).astype('float32')
> ValueError: cannot reshape array of size 496500 into shape (300,300,3)

Besides, FEA_HEIGHT4, FEA_WIDTH4, FEA_HEIGHT3, FEA_WIDTH3 are needed to be reset. FEA_HEIGHT4 and FEA_WIDTH4 are the size of the feature map of conv4_3. FEA_HEIGHT3 and FEA_WIDTH3 are the size of the feature map of conv3_3.

**Comment by niuxiansen2** [comment]
> > hello @ZongxuPan
> > Is the size of the input image fixed? Why do I encounter the following problems with my own data set?
> > Traceback (most recent call last):
> > File "Drbox.py", line 469, in
> > net.train()
> > File "Drbox.py", line 284, in train
> > input_im[k] = im.reshape(IM_HEIGHT, IM_WIDTH, IM_CDIM).astype('float32')
> > ValueError: cannot reshape array of size 496500 into shape (300,300,3)
> 
> Besides, FEA_HEIGHT4, FEA_WIDTH4, FEA_HEIGHT3, FEA_WIDTH3 are needed to be reset. FEA_HEIGHT4 and FEA_WIDTH4 are the size of the feature map of conv4_3. FEA_HEIGHT3 and FEA_WIDTH3 are the size of the feature map of conv3_3.

Okay, I understand，Thank you very much!

**Comment by niuxiansen2** [comment]
When I train with my own data set, I don't know how to set the values of PRIOR_HEIGHTS and PRIOR_WEIGHTS. What is your method?

**Comment by niuxiansen2** [comment]
> > hello @ZongxuPan
> > Is the size of the input image fixed? Why do I encounter the following problems with my own data set?
> > Traceback (most recent call last):
> > File "Drbox.py", line 469, in
> > net.train()
> > File "Drbox.py", line 284, in train
> > input_im[k] = im.reshape(IM_HEIGHT, IM_WIDTH, IM_CDIM).astype('float32')
> > ValueError: cannot reshape array of size 496500 into shape (300,300,3)
> 
> Besides, FEA_HEIGHT4, FEA_WIDTH4, FEA_HEIGHT3, FEA_WIDTH3 are needed to be reset. FEA_HEIGHT4 and FEA_WIDTH4 are the size of the feature map of conv4_3. FEA_HEIGHT3 and FEA_WIDTH3 are the size of the feature map of conv3_3.

When I train with my own data set, I don't know how to set the values of PRIOR_HEIGHTS and PRIOR_WEIGHTS. What is your method?
